trunk: check_cases: (1) script now also checks for differences in FinalParam.out (produced if opti=.true.) otherwise no file would be checked in optimization mode, (2) updated output_save for opti cases (03 and 06) which was never checked and changed due to several bugs in the past

diff --git a/check/check_mhm_cases b/check/check_mhm_cases
--- a/check/check_mhm_cases
+++ b/check/check_mhm_cases
@@ -153,7 +153,7 @@ function cleanup ()
 
     # everything in case_?? dirs
     case_dirs=$(\ls -d case_*)
-    rmfiles="dds_results.out ${mhm_exe} cdo.*.terminal mhm_terminal.*.out diff.*.terminal"
+    rmfiles="dds_results.out ${mhm_exe} cdo.*.terminal mhm_terminal.*.out diff*.*.terminal"
     rmdirs="output_b1 output_b2"
 
     # using brace expansion
@@ -254,16 +254,16 @@ for irelease in ${release} ; do
             echo '         Release:  '${irelease}
             make system=${system} compiler=${compiler} release=${irelease} PROGNAME=${mhm_exe} openmp= cleanclean > /dev/null
             if [[ ${thread} -eq 0 ]] ; then
-		          echo '         OpenMP:   False'
-		          make system=${system} compiler=${compiler} release=${irelease} PROGNAME=${mhm_exe} openmp= > /dev/null
+		echo '         OpenMP:   False'
+		make system=${system} compiler=${compiler} release=${irelease} PROGNAME=${mhm_exe} openmp= > /dev/null
             else
-		          echo '         OpenMP:   True'
-		          echo '         Threads:  '${thread}
-		          make system=${system} compiler=${compiler} release=${irelease} PROGNAME=${mhm_exe} openmp=true > /dev/null
-		          export OMP_NUM_THREADS=${thread}
+		echo '         OpenMP:   True'
+		echo '         Threads:  '${thread}
+		make system=${system} compiler=${compiler} release=${irelease} PROGNAME=${mhm_exe} openmp=true > /dev/null
+		export OMP_NUM_THREADS=${thread}
             fi
 
-	          # run checks
+	    # run checks
             cd check
             case_dirs=$(\ls -d case_*)
             #case_dirs=$(\ls -d case_02)
@@ -288,21 +288,25 @@ for irelease in ${release} ; do
                 # mhm was running till the end?
                 found=$(grep 'mHM: Finished!' mhm_terminal.${pid}.out)
                 if [[ ${found} == 'mHM: Finished!' ]] ; then
-                  
+                    
                     nRecordsDiffer=0
                     cd output_save
-		                set +e
-                    nc_files=$(\ls *.nc 2> /dev/null) # causes failure if no such file exists
-		                discharge_files=$(\ls *daily_discharge.out 2> /dev/null) # causes failure if no such file exists
-		                set -e
-		                if [[ -z ${nc_files} ]] ; then
-			                echo '   No NetCDF files written!'
-		                fi
-		                if [[ -z ${discharge_files} ]] ; then
-			                echo '   No discharge files written!'
-		                fi
+		    set +e
+                    nc_files=$(\ls *.nc 2> /dev/null)                        # causes failure if no such file exists
+		    discharge_files=$(\ls *daily_discharge.out 2> /dev/null) # causes failure if no such file exists
+		    finalpara_files=$(\ls *FinalParam.out 2> /dev/null)      # causes failure if no such file exists
+		    set -e
+		    if [[ -z ${nc_files} ]] ; then
+			echo '   No NetCDF     files written!'
+		    fi
+		    if [[ -z ${discharge_files} ]] ; then
+			echo '   No discharge  files written!'
+		    fi
+		    if [[ -z ${finalpara_files} ]] ; then
+			echo '   No FinalParam files written!'
+		    fi
                     cd ..
-		                echo ''
+		    echo ''
 
                     # compare NetCDF outputs in output_b1/ with reference in output_save/
                     for nc_file in ${nc_files} ; do
@@ -324,13 +328,12 @@ for irelease in ${release} ; do
                     done
 
 		    # compare daily_discharge outputs in output_b1/ with reference in output_save/
-		    # if [[ -e output_save/daily_discharge.out ]] ; then
 		    for discharge_file in ${discharge_files} ; do
 			echo '   *  diff output_save/'${discharge_file}' output_b1/'${discharge_file}
 			set +e
-			diff output_save/${discharge_file} output_b1/${discharge_file} > diff.${pid}.terminal
+			diff output_save/${discharge_file} output_b1/${discharge_file} > diff1.${pid}.terminal
 			set -e
-			iRecordsDiffer=$(echo $(wc -l diff.${pid}.terminal) | cut -d ' ' -f 1)
+			iRecordsDiffer=$(echo $(wc -l diff1.${pid}.terminal) | cut -d ' ' -f 1)
 			if [[ ${iRecordsDiffer} -gt 0 ]] ; then
 			    iRecordsDiffer=$(( (iRecordsDiffer - 2) / 2 ))
 			fi
@@ -348,7 +351,33 @@ for irelease in ${release} ; do
 			fi
 			echo ''
 		    done
-			
+
+		    # compare FinalParam.out outputs in output_b1/ with reference in output_save/
+		    # --> only for optimization cases
+		    for finalpara_file in ${finalpara_files} ; do
+			echo '   *  diff output_save/'${finalpara_file}' output_b1/'${finalpara_file}
+			set +e
+			diff output_save/${finalpara_file} output_b1/${finalpara_file} > diff2.${pid}.terminal
+			set -e
+			iRecordsDiffer=$(echo $(wc -l diff2.${pid}.terminal) | cut -d ' ' -f 1)
+			if [[ ${iRecordsDiffer} -gt 0 ]] ; then
+			    iRecordsDiffer=$(( (iRecordsDiffer - 2) / 2 ))
+			fi
+			nRecordsDiffer=$((nRecordsDiffer+iRecordsDiffer))
+			nRecordsDiffer_allCases=$((nRecordsDiffer_allCases+iRecordsDiffer))
+			echo '      Number of records that differ: '${iRecordsDiffer}
+			if [[ ${iRecordsDiffer} -gt 0 ]] ; then
+                            echo '            --------------------------------------'
+                            echo '                  Details                         '
+                            echo '            --------------------------------------'
+                            set +e
+			    diff output_save/${finalpara_file} output_b1/${finalpara_file}
+			    set -e
+                            echo '            --------------------------------------'
+			fi
+			echo ''
+		    done
+		    
                     echo '   Total Number of records that differ: '${nRecordsDiffer}
 
                     if [[ ${nRecordsDiffer} -eq 0 ]] ; then
